// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmermysszjoclywaizkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZXJteXNzempvY2x5d2Fpemt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzc2MDQsImV4cCI6MjA2NzgxMzYwNH0.sgXe-jh5HxZ6JFi4d7KIVq-PaiCWyOZEPbW01B5oKQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});